export const SIMULATIONS = [
    { id: "SIM-01", score: 83.91, color: "#00e5a0" },
    { id: "SIM-02", score: 66.996, color: "#f0b040" },
    { id: "SIM-03", score: 64, color: "#f0b040" },
    { id: "SIM-04", score: 69, color: "#f0b040" },
    { id: "SIM-05", score: 91, color: "#00e5a0" },
    { id: "SIM-06", score: 85.661, color: "#00e5a0" },
    { id: "SIM-07", score: 74, color: "#f0b040" },
    { id: "SIM-08", score: 93, color: "#00e5a0" },
    { id: "SIM-09", score: 84, color: "#00e5a0" },
];
export const SIMULATIONS_CARDS = [
    {
        id: "SIM-05",
        name: "Separation Distance",
        domain: "Fault classification",
        progress: "Step 8/8",
        ref: "IEC 60079-11 Cl.6.3",
        eta: "0m",
        status: "Complete",
        color: "green",
    },
    {
        id: "SIM-01",
        name: "Spark Energy Budget",
        domain: "Intrinsic safety",
        progress: "Step 5/8",
        ref: "IEC 60079-11 Table 5",
        eta: "9m",
        status: "Running",
        color: "blue",
    },
    {
        id: "SIM-02",
        name: "FEM Thermal Rise",
        domain: "Thermal compliance",
        progress: "Step 6/8",
        ref: "IEC 60079-0 Cl.1.5.3",
        eta: "6m",
        status: "Running",
        color: "blue",
    },
    {
        id: "SIM-06",
        name: "Component T–Class",
        domain: "Temperature class",
        progress: "Step 4/8",
        ref: "IEC 60079-0 Table 2a/2b",
        eta: "11m",
        status: "Running",
        color: "blue",
    },
    {
        id: "SIM-07",
        name: "Documentation Evidence",
        domain: "Technical file",
        progress: "Step 7/8",
        ref: "IEC 60079-0 Cl.1.24",
        eta: "3m",
        status: "Needs review",
        color: "amber",
    },
    {
        id: "SIM-08",
        name: "Ingress & Enclosure",
        domain: "Mechanical protection",
        progress: "Step 8/8",
        ref: "IEC 60079-0 Cl.1.26",
        eta: "0m",
        status: "Complete",
        color: "green",
    },
    {
        id: "SIM-03",
        name: "PCB Track T–Class",
        domain: "Track thermal class",
        progress: "Step 2/8",
        ref: "IEC 60079-11 Annex F",
        eta: "waiting",
        status: "Blocked",
        color: "red",
    },
    {
        id: "SIM-04",
        name: "Friction Hotspots",
        domain: "Mechanical ignition",
        progress: "Step 1/8",
        ref: "IEC 60079-0 Cl.1.8",
        eta: "waiting",
        status: "Queued",
        color: "amber",
    },
    {
        id: "SIM-09",
        name: "Final Zone Sweep",
        domain: "Certification path",
        progress: "Step 0/8",
        ref: "IEC 60079-0/-11 final",
        eta: "final",
        status: "Locked",
        color: "gray",
    },
];
export const GAPS = [
    {
        id: "SIM-05",
        sim: "SIM-05",
        clause: "IEC 60079-11 Cl.6.3.12",
        desc: "Countable fault budget exceeded on U3.4 to J2.1",
        severity: "Critical",
        status: "Open",
        component: "U3.4",
        downstream: "J2.1",
        fix: "Reduce fault budget by redesigning track spacing",
        margin: "Requires 0.2mm additional clearance",
    },
    {
        id: "SIM-02",
        sim: "SIM-02",
        clause: "IEC 60079-0 Cl.5.3.2",
        desc: "Enclosure hotspot exceeds T4 class under 55°C ambient by 3.2°C",
        severity: "Major",
        status: "In Review",
        component: "Enclosure",
        downstream: "Thermal path",
        fix: "Add heatsink or improve airflow",
        margin: "Reduce hotspot by 3.2°C",
    },
    {
        id: "SIM-07",
        sim: "SIM-07",
        clause: "IEC 60079-0 Cl.24.2",
        desc: "Technical file missing routine dielectric test method evidence link",
        severity: "Minor",
        status: "Fixed",
        component: "Documentation",
        downstream: "Compliance file",
        fix: "Attach dielectric test evidence",
        margin: "Verified by QA",
    },
    {
        id: "SIM-03",
        sim: "SIM-03",
        clause: "IEC 60079-11 Annex F",
        desc: "Copper track T-class margin unknown until SIM-02 final boundary signed",
        severity: "Major",
        status: "Open",
        component: "Copper track",
        downstream: "SIM-02 boundary",
        fix: "Clarify margin and finalize boundary conditions",
        margin: "Pending signature",
    },
];
export const SCORECARD = {
    overall: 84,
    zones: { zone0: 61, zone1: 84 },
    dimensions: [
        { label: "Standards Coverage", score: 92, color: "#00e5a0" },
        { label: "Thermal Compliance", score: 81, color: "#f0b040" },
        { label: "Spark Safety", score: 76, color: "#f06046" },
        { label: "Separation Compliance", score: 88, color: "#00e5a0" },
        { label: "Documentation", score: 74, color: "#f0b040" },
        { label: "Cert Path Confidence", score: 86, color: "#00e5a0" },
    ],
};

export const SCORE_DIMS = [];
export const LIVE_EVENTS = [
    {
        actor: "AI-17",
        time: "now",
        text: "SIM-05 completed: 2 countable faults detected near U3",
        kind: "complete",
    },
    {
        actor: "AI-05",
        time: "2m",
        text: "Major gap raised for IEC 60079–11 Cl.6.3.12 clearance margin",
        kind: "gap",
    },
    {
        actor: "Copilot",
        time: "4m",
        text: "Increase separation at U3 pin 4 by 0.4mm",
        kind: "recommend",
    },
    {
        actor: "Maya R.",
        time: "8m",
        text: "Compliance manager approved thermal evidence link",
        kind: "action",
    },
];
export const TECH_SECTIONS = [
    { name: "Product description", evidence: "BOM + enclosure STEP", progress: "100%" },
    { name: "Standards matrix", evidence: "AI–05 clause mapping", progress: "92%" },
    { name: "Ignition hazard assessment", evidence: "SIM–01 / SIM–05", progress: "78%" },
    { name: "Thermal assessment", evidence: "SIM–02 FEM report", progress: "83%" },
    { name: "Routine test method", evidence: "SIM–07 draft needed", progress: "46%" },
    { name: "Marking schedule", evidence: "SIM–09 pending", progress: "69%" },
];

export const CITATIONS = [
    { clause: "IEC 60079-0 Cl.24.2", ref: "PDF p.118", status: "Verified" },
    { clause: "IEC 60079-11 Table 5", ref: "PDF p.42", status: "Verified" },
    { clause: "IEC 60079-0 Cl.5.3.2", ref: "PDF p.31", status: "Verified" },
    { clause: "IEC 60079-11 Cl.6.3.12", ref: "PDF p.57", status: "In Review" },
];

